version: 2
updates:
  - package-ecosystem: "npm" # or your specific ecosystem
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
