version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  example-job:
    docker:
    # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test:ci
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
workflows:
  example-workflow:
    jobs:
      - example-job