version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  example-job:
    docker:
    # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: # run tests
          name: test
          command: npm run test:ci
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
workflows:
  example-workflow:
    jobs:
      - example-job